<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MM4I4GD" failures="1" tests="7" name="com.mycompany.testmavin.TestMavinIT" time="79.948" errors="0" timestamp="29 Dec 2022 16:31:20 GMT">
  <testcase classname="com.mycompany.testmavin.TestMavinIT" name="testOpenDrawer" time="4.094"/>
  <testcase classname="com.mycompany.testmavin.TestMavinIT" name="testTabs" time="37.886"/>
  <testcase classname="com.mycompany.testmavin.TestMavinIT" name="testLogin" time="14.245"/>
  <testcase classname="com.mycompany.testmavin.TestMavinIT" name="testSelectEmployeeStatusAndSearch" time="9.879"/>
  <testcase classname="com.mycompany.testmavin.TestMavinIT" name="testOneItemPimAdd" time="0.000">
    <failure message="
The data provider is trying to pass 17 parameters but the method com.mycompany.testmavin.TestMavinIT#testOneItemPimAdd takes 19 and TestNG is unable in inject a suitable object" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 17 parameters but the method com.mycompany.testmavin.TestMavinIT#testOneItemPimAdd takes 19 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1361)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1225)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 17 out of bounds for length 17
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1359)
	... 21 more
]]>
    </failure>
  </testcase> <!-- testOneItemPimAdd -->
  <testcase classname="com.mycompany.testmavin.TestMavinIT" name="testSignOut" time="3.715"/>
  <testcase classname="com.mycompany.testmavin.TestMavinIT" name="testDeleteItem" time="10.129"/>
</testsuite> <!-- com.mycompany.testmavin.TestMavinIT -->
